---
- hosts: {{ servername }} 
  gather_facts: 0
  tasks:
  - name: "DISPLAY SERVER DETAILS"
    shell: |
	date;
	uname -a
	sar -r 1 3
	df -h /
	ls -alrth /
    register: output

  - debug: var=output.stdout
...
