---
- hosts: "{{ servername }}"
  gather_facts: 0
  tasks:
  - name: "DISPLAY SERVER DETAILS"
    shell: date
    register: date_out

  - name: "DISPLAY UNAME"
    shell: uname -a
    register: unmae_out

  - name: "DISPLAY file system DETAILS"
    shell: df -h
    register: file_system_out

  - debug: var=date_out.stdout
  - debug: var=unmae_out.stdout
  - debug: var=file_system_out.stdout
...
